import 'dart:io';
import '../models/changed_file.dart';

class ExportResult {
  final int totalFiles;
  final int copiedFiles;
  final int skippedFiles;
  final int deletedFilesCount;
  final bool scriptGenerated;
  final List<String> errors;

  const ExportResult({
    required this.totalFiles,
    required this.copiedFiles,
    required this.skippedFiles,
    this.deletedFilesCount = 0,
    this.scriptGenerated = false,
    required this.errors,
  });

  bool get hasErrors => errors.isNotEmpty;
  bool get isSuccess => (copiedFiles > 0 || deletedFilesCount > 0) && !hasErrors;
}

class ExportService {
  /// Generates a bash script `delete_files.sh` at [destinationPath] to remove deleted files on server.
  Future<bool> generateDeleteScript({
    required String destinationPath,
    required List<ChangedFile> deletedFiles,
  }) async {
    if (deletedFiles.isEmpty) return false;
    try {
      final scriptFile = File('$destinationPath/delete_files.sh');
      final buffer = StringBuffer();
      buffer.writeln('#!/bin/bash');
      buffer.writeln('# Auto-generated by Deploy Packager');
      buffer.writeln('# Run this script in the root deployment folder on your server.');
      buffer.writeln();
      buffer.writeln('echo "Deleting ${deletedFiles.length} removed file(s)..."');
      for (final file in deletedFiles) {
        buffer.writeln('rm -f "${file.relativePath}"');
      }
      buffer.writeln('echo "Cleanup complete! Removed ${deletedFiles.length} file(s)."');
      buffer.writeln();
      buffer.writeln('# Self-destruct this script');
      buffer.writeln('rm -f -- "\$0"');

      await scriptFile.writeAsString(buffer.toString());

      if (!Platform.isWindows) {
        try {
          await Process.run('chmod', ['+x', scriptFile.path]);
        } catch (_) {}
      }
      return true;
    } catch (_) {
      return false;
    }
  }

  /// Copies active (non-deleted) files from [sourcePath] to [destinationPath],
  /// preserving the relative directory structure.
  ///
  /// Calls [onProgress] with (current, total) for each file processed.
  Future<ExportResult> exportFiles({
    required String sourcePath,
    required String destinationPath,
    required List<ChangedFile> files,
    int deletedFilesCount = 0,
    bool scriptGenerated = false,
    void Function(int current, int total)? onProgress,
  }) async {
    int copiedFiles = 0;
    int skippedFiles = 0;
    final errors = <String>[];

    final filesToCopy = files.where((f) => !f.isDeleted).toList();

    if (filesToCopy.isEmpty) {
      return ExportResult(
        totalFiles: files.length,
        copiedFiles: 0,
        skippedFiles: 0,
        deletedFilesCount: deletedFilesCount,
        scriptGenerated: scriptGenerated,
        errors: errors,
      );
    }

    for (int i = 0; i < filesToCopy.length; i++) {
      final file = filesToCopy[i];
      try {
        final sourceFile = File('$sourcePath/${file.relativePath}');

        if (!await sourceFile.exists()) {
          skippedFiles++;
          errors.add('File not found: ${file.relativePath}');
          onProgress?.call(i + 1, filesToCopy.length);
          continue;
        }

        final destFile = File('$destinationPath/${file.relativePath}');

        // Create parent directories recursively
        await destFile.parent.create(recursive: true);

        // Copy the file
        await sourceFile.copy(destFile.path);
        copiedFiles++;
      } catch (e) {
        skippedFiles++;
        errors.add('Error copying ${file.relativePath}: $e');
      }

      onProgress?.call(i + 1, filesToCopy.length);
    }

    return ExportResult(
      totalFiles: files.length,
      copiedFiles: copiedFiles,
      skippedFiles: skippedFiles,
      deletedFilesCount: deletedFilesCount,
      scriptGenerated: scriptGenerated,
      errors: errors,
    );
  }
}
